### PR TITLE
Ng10 upgrade

### PR DESCRIPTION
**Pull request by Toktik**
Upgraded the lib to Angular 10
Also added demos for Angular 9 and Angular 10

### CODE REVIEW

**Review by Yalrafih — APPROVED** [review]
@DethAriel can you please take a look, best to review without whitespace changes

**Comment by DethAriel** [comment]
Hi @Toktik , and thank you for the contribution!

Was there any particular reason to drop v6 support?
Also, while I do appreciate your intention to replace whitespace, please try to ensure that your PR only touches the files which are relevant for Angular 9/10 support. If I understand correctly, your changes can be boiled down to peerDependency updates, is that right? Or did I miss something?

**Comment by Toktik** [comment]
@DethAriel v6 has been dropped because of nodejs version and typescript compiler, which is shared between all the demos.

The main change is the peerDependency change. Few other changes as well
- Some TSLint rules deprecation (because of stricter compiler checks).
- Some other libraries bumped, such as tslib

I can create a new branch, where I'll make sure whitespaces are not affected, commit guidelines are respected and will make sure demos build properly. @DethAriel let me know if I should do it.

**Comment by DethAriel** [comment]
@Toktik I'm currently at a point where I was able to make v9 demos work (also without dropping Angular v6 support, looks like). Let me play around with v10 for a day more, and I'll get back to you. How does that sound?

**Comment by DethAriel** [comment]
@Toktik I've updated the lib to be compatible with both Angular 9 & Angular 10 in terms of dependencies. With that, I will close your pull request. But I want to thank you from the bottom of my heart for your readiness to help with this -- it gave me strength to pursue this, and I was able to use your pull request as a reference for my own 🙏

With that said, if you find any additional improvements beyond the ones I did (and I'm sure there are at least a dozen) -- please do not hesitate to reach out and/or open a new pull request.

Thank you very much!

**Pull request closed without merging**
