### PR TITLE
refactor(component): add the ability to change the lang dynamically

### LINKED ISSUE #25: Question: dynamic translation of recaptcha text
Is it possible to dynamically change the language of the recaptcha when it is already loaded on the screen?

### PR DESCRIPTION
**Pull request by keybeth**
Closes #25

### CODE REVIEW

**Comment by DethAriel** [comment]
Oh, that looks great, thank you for the PR! I'll try to take a closer look at it soon. In the meanwhile, could you please share some of the ways that this is working? Previously when I was trying to do something like that, the behavior around the time when recaptcha was about to be reset was quite funky 😝

**Comment by DethAriel** [comment]
@keybeth after taking a closer look, it appears as if this PR is using undocumented reCAPTCHA capabilities. I haven't found any references in the public reCAPTCHA API around that, but I'm happy to be proven wrong, though :)

If the API of the internal `iframe` will turn out to be public, I will gladly discuss the PR further. Until then, I'm afraid I cannot accept it. The reason is - if at some point reCAPTCHA devs will make a decision to rename the inner `hl` parameter to something else - the code might break and not behave in an expected way.

I would potentially be open to include this new `lang` parameter if it will be named in a way that makes it obvious for the consumers of the API that it is unstable, e.g. `unsafe_lang`, `experimental_lang` or something similar.

What would your thoughts be?

**Comment by keybeth** [comment]
Indeed, the way in which it is being carried out is experimental, since the information corresponding to the frame is not available.

If we include `unsafe_lang` parameter, the option to set the language should also remain through the `RECAPTCHA_LANGUAGE` service?

**Comment by DethAriel** [comment]
Yes, I think it should, since it's kinda the only stable way of performing a language change. It would be good to do that anyway to avoid a breaking change.

Just to make sure that your expectations are set up correctly - I still can't guarantee that this will get into the lib. I believe using such a parameter will be tempting for some users, and they might rely on it working without fully understanding the potential drawbacks

**Comment by dfranckj** [comment]
Hey guys, any news on this PR?
Anything I can do to help you out?

I'm waiting to use this feature on my project.

Thanks!

**Comment by DethAriel** [comment]
hey @dfranckj !

No news on this PR. At this time I will decline it for a couple of reasons, the main one being that the functionality described here appears to be core to the library, whereas it uses internal undocumented feature of reCAPTCHA.

I would be open to accept a PR that will decouple an undocumented feature from stable API. One of the ways it could be implemented would go like this:

* A plugin-enabled version of `<re-captcha>` component (e.g. the one which will accept a new `@Input() pluginData` parameter of potentially arbitrary form;
* An experimental `ng-recaptcha-lang` plugin which will have the functionality of this very PR.

This feature seems a bit off to me, given the angular-proposed i18n flow (which should be covered already by `RECAPTCHA_LANGUAGE`) and the reCAPTCHA auto language detection feature.

If you (or anybody else reading this) feel like this is something you would be interesting in implementing - feel free to create an issue with a technical proposal. We'll engage in a discussion there.

**Pull request closed without merging**
