### PR TITLE
Update to Angular v17

### PR DESCRIPTION
**Pull request by medbenmakhlouf**

### CODE REVIEW

**Comment by medbenmakhlouf** [comment]
@DethAriel , would you mind to take a look ? Thanks

**Comment by bsplosion** [comment]
> I think you missed the compatibility info in the readme

Pretty sure they understand the compatibility info in the readme - it clearly states compatibility for versions through `16.x.x` (for `ng-recaptcha@12.x.x`).  It also states that "Starting with ng-recaptcha@7, only one version of Angular will be supported".  This clearly indicates that for Angular `17.x.x` compatibility there are changes required, hence the ticket.

**Comment by DethAriel** [comment]
Thx for the PR @medbenmakhlouf . Let me take care of it

**Comment by DethAriel** [comment]
I merged this via cherry-picking from your pull request. I did squash some commits, and modified the commit messages. Thank you for your contribution @medbenmakhlouf !

**Comment by carriquiry-g** [comment]
@DethAriel when are you planning on releasing the v13 update?

**Pull request closed without merging**
