### PR TITLE
fix: catch recaptcha error in recaptcha-v3.service

### PR DESCRIPTION
**Pull request by caojs**
Catch recaptcha error

Screenshot from 2019-10-30 09-15-40

### CODE REVIEW

**Review by Smip — APPROVED** [review]
Great fix!

**Comment by DethAriel** [comment]
Hi @caojs ! Thx for submitting this PR!

I would like to understand what scenario exactly does this PR help to address?

As a way of simulating a failure, I tried to execute an action while the browser was in offline mode, but this still resulted in unhandled promise rejection 😕 Did I do this wrong? Does this PR try to address #175?

**Comment by Smip** [comment]
> As a way of simulating a failure, I tried to execute an action while the browser was in offline mode, but this still resulted in unhandled promise rejection 😕 Did I do this wrong? Does this PR try to address #175?

I added a catchError pipe to the execute stream and if there will be a promise rejection I can handle it. Try it

**Comment by DethAriel** [comment]
@Smip thx for the explainer, yes, you're right, I was testing it the wrong way previously.

This PR does allow for error handling, however it only makes the `onExecute` subject complete upon encountering an error. I don't think this is the right behavior (as, for example, offline errors are recoverable). With that, I will accept the contribution by @caojs , but update the API usage to ensure that `onExecute` subject continues to receive values

**Pull request merged**
